<?php

/**
 * BaseLyraRegionComponent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $region_id
 * @property integer $component_id
 * @property array $params
 * @property LyraRegion $Region
 * @property LyraComponent $Component
 * 
 * @method integer             getRegionId()     Returns the current record's "region_id" value
 * @method integer             getComponentId()  Returns the current record's "component_id" value
 * @method array               getParams()       Returns the current record's "params" value
 * @method LyraRegion          getRegion()       Returns the current record's "Region" value
 * @method LyraComponent       getComponent()    Returns the current record's "Component" value
 * @method LyraRegionComponent setRegionId()     Sets the current record's "region_id" value
 * @method LyraRegionComponent setComponentId()  Sets the current record's "component_id" value
 * @method LyraRegionComponent setParams()       Sets the current record's "params" value
 * @method LyraRegionComponent setRegion()       Sets the current record's "Region" value
 * @method LyraRegionComponent setComponent()    Sets the current record's "Component" value
 * 
 * @package    lyra
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLyraRegionComponent extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('region_component');
        $this->hasColumn('region_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('component_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('params', 'array', null, array(
             'type' => 'array',
             ));

        $this->option('symfony', array(
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('LyraRegion as Region', array(
             'local' => 'region_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('LyraComponent as Component', array(
             'local' => 'component_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $sortable0 = new Doctrine_Template_Sortable(array(
             'uniqueBy' => 
             array(
              0 => 'region_id',
             ),
             ));
        $this->actAs($sortable0);
    }
}