<?php

/**
 * BaseLyraMenu
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $parent_id
 * @property string $type
 * @property integer $ctype_id
 * @property integer $object_id
 * @property integer $list_id
 * @property string $name
 * @property array $params
 * @property LyraMenu $MenuParent
 * @property LyraContentType $MenuContentType
 * @property LyraArticle $MenuItemObject
 * @property LyraRoute $MenuItemList
 * @property Doctrine_Collection $LyraMenu
 * 
 * @method integer             getId()              Returns the current record's "id" value
 * @method integer             getParentId()        Returns the current record's "parent_id" value
 * @method string              getType()            Returns the current record's "type" value
 * @method integer             getCtypeId()         Returns the current record's "ctype_id" value
 * @method integer             getObjectId()        Returns the current record's "object_id" value
 * @method integer             getListId()          Returns the current record's "list_id" value
 * @method string              getName()            Returns the current record's "name" value
 * @method array               getParams()          Returns the current record's "params" value
 * @method LyraMenu            getMenuParent()      Returns the current record's "MenuParent" value
 * @method LyraContentType     getMenuContentType() Returns the current record's "MenuContentType" value
 * @method LyraArticle         getMenuItemObject()  Returns the current record's "MenuItemObject" value
 * @method LyraRoute           getMenuItemList()    Returns the current record's "MenuItemList" value
 * @method Doctrine_Collection getLyraMenu()        Returns the current record's "LyraMenu" collection
 * @method LyraMenu            setId()              Sets the current record's "id" value
 * @method LyraMenu            setParentId()        Sets the current record's "parent_id" value
 * @method LyraMenu            setType()            Sets the current record's "type" value
 * @method LyraMenu            setCtypeId()         Sets the current record's "ctype_id" value
 * @method LyraMenu            setObjectId()        Sets the current record's "object_id" value
 * @method LyraMenu            setListId()          Sets the current record's "list_id" value
 * @method LyraMenu            setName()            Sets the current record's "name" value
 * @method LyraMenu            setParams()          Sets the current record's "params" value
 * @method LyraMenu            setMenuParent()      Sets the current record's "MenuParent" value
 * @method LyraMenu            setMenuContentType() Sets the current record's "MenuContentType" value
 * @method LyraMenu            setMenuItemObject()  Sets the current record's "MenuItemObject" value
 * @method LyraMenu            setMenuItemList()    Sets the current record's "MenuItemList" value
 * @method LyraMenu            setLyraMenu()        Sets the current record's "LyraMenu" collection
 * 
 * @package    lyra
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLyraMenu extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('menus');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('parent_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('type', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('ctype_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('object_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('list_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('params', 'array', null, array(
             'type' => 'array',
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('LyraMenu as MenuParent', array(
             'local' => 'parent_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('LyraContentType as MenuContentType', array(
             'local' => 'ctype_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('LyraArticle as MenuItemObject', array(
             'local' => 'object_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('LyraRoute as MenuItemList', array(
             'local' => 'list_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('LyraMenu', array(
             'local' => 'id',
             'foreign' => 'parent_id'));

        $nestedset0 = new Doctrine_Template_NestedSet(array(
             'hasManyRoots' => true,
             'rootColumnName' => 'root_id',
             ));
        $this->actAs($nestedset0);
    }
}