<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseLyraContentTypeCatalog extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('content_type_catalog');
        $this->hasColumn('ctype_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '4',
             ));
        $this->hasColumn('catalog_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '4',
             ));
    }

    public function setUp()
    {
        $this->hasOne('LyraContentType as ContentType', array(
             'local' => 'ctype_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('LyraCatalog as Catalog', array(
             'local' => 'catalog_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}