<?php

/**
 * BaseLyraContent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ctype_id
 * @property clob $params
 * 
 * @method integer     getCtypeId()  Returns the current record's "ctype_id" value
 * @method clob        getParams()   Returns the current record's "params" value
 * @method LyraContent setCtypeId()  Sets the current record's "ctype_id" value
 * @method LyraContent setParams()   Sets the current record's "params" value
 * 
 * @package    lyra
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseLyraContent extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('lyra_content');
        $this->hasColumn('ctype_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('params', 'clob', null, array(
             'type' => 'clob',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}