<?php

/**
 * BaseLyraRegion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property Doctrine_Collection $RegionComponents
 * @property Doctrine_Collection $RefComponents
 * 
 * @method integer             getId()               Returns the current record's "id" value
 * @method string              getName()             Returns the current record's "name" value
 * @method Doctrine_Collection getRegionComponents() Returns the current record's "RegionComponents" collection
 * @method Doctrine_Collection getRefComponents()    Returns the current record's "RefComponents" collection
 * @method LyraRegion          setId()               Sets the current record's "id" value
 * @method LyraRegion          setName()             Sets the current record's "name" value
 * @method LyraRegion          setRegionComponents() Sets the current record's "RegionComponents" collection
 * @method LyraRegion          setRefComponents()    Sets the current record's "RefComponents" collection
 * 
 * @package    lyra
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLyraRegion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('regions');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('LyraComponent as RegionComponents', array(
             'refClass' => 'LyraRegionComponent',
             'local' => 'region_id',
             'foreign' => 'component_id'));

        $this->hasMany('LyraRegionComponent as RefComponents', array(
             'local' => 'id',
             'foreign' => 'region_id',
             'orderBy' => 'position'));
    }
}