<?php

/**
 * BaseLyraContentTypeCatalog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ctype_id
 * @property integer $catalog_id
 * @property LyraContentType $ContentType
 * @property LyraCatalog $Catalog
 * 
 * @method integer                getCtypeId()     Returns the current record's "ctype_id" value
 * @method integer                getCatalogId()   Returns the current record's "catalog_id" value
 * @method LyraContentType        getContentType() Returns the current record's "ContentType" value
 * @method LyraCatalog            getCatalog()     Returns the current record's "Catalog" value
 * @method LyraContentTypeCatalog setCtypeId()     Sets the current record's "ctype_id" value
 * @method LyraContentTypeCatalog setCatalogId()   Sets the current record's "catalog_id" value
 * @method LyraContentTypeCatalog setContentType() Sets the current record's "ContentType" value
 * @method LyraContentTypeCatalog setCatalog()     Sets the current record's "Catalog" value
 * 
 * @package    lyra
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLyraContentTypeCatalog extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('content_type_catalog');
        $this->hasColumn('ctype_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('catalog_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('LyraContentType as ContentType', array(
             'local' => 'ctype_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('LyraCatalog as Catalog', array(
             'local' => 'catalog_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}