<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseLyraArticleLabel extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('article_label');
        $this->hasColumn('article_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '4',
             ));
        $this->hasColumn('label_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '4',
             ));
    }

    public function setUp()
    {
        $this->hasOne('LyraArticle as Article', array(
             'local' => 'article_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('LyraLabel as Label', array(
             'local' => 'label_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}