<?php

/**
 * BaseLyraContent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ctype_id
 * @property string $path
 * @property clob $params
 * 
 * @method integer     getCtypeId()  Returns the current record's "ctype_id" value
 * @method string      getPath()     Returns the current record's "path" value
 * @method clob        getParams()   Returns the current record's "params" value
 * @method LyraContent setCtypeId()  Sets the current record's "ctype_id" value
 * @method LyraContent setPath()     Sets the current record's "path" value
 * @method LyraContent setParams()   Sets the current record's "params" value
 * 
 * @package    lyra
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLyraContent extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('lyra_content');
        $this->hasColumn('ctype_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('path', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('params', 'clob', null, array(
             'type' => 'clob',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}