<?php

/**
 * BaseLyraArticleLabel
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $article_id
 * @property integer $label_id
 * @property LyraArticle $Article
 * @property LyraLabel $Label
 * 
 * @method integer          getArticleId()  Returns the current record's "article_id" value
 * @method integer          getLabelId()    Returns the current record's "label_id" value
 * @method LyraArticle      getArticle()    Returns the current record's "Article" value
 * @method LyraLabel        getLabel()      Returns the current record's "Label" value
 * @method LyraArticleLabel setArticleId()  Sets the current record's "article_id" value
 * @method LyraArticleLabel setLabelId()    Sets the current record's "label_id" value
 * @method LyraArticleLabel setArticle()    Sets the current record's "Article" value
 * @method LyraArticleLabel setLabel()      Sets the current record's "Label" value
 * 
 * @package    lyra
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLyraArticleLabel extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('article_label');
        $this->hasColumn('article_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('label_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('LyraArticle as Article', array(
             'local' => 'article_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('LyraLabel as Label', array(
             'local' => 'label_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}