lyra_user:
  class: sfDoctrineRouteCollection
  options:
    model:                sfGuardUser
    module:               user
    prefix_path:          /user
    column:               id
    with_wildcard_routes: true

lyra_component_edit_params:
  url: /component/:region_id/:id/params
  class: sfDoctrineRoute
  options:
    type: object
    model: LyraRegionComponent
    method: findItem
  param:
    module: component
    action: params
  requirements:
    sf_method: [get]

lyra_component_update_params:
  url: /component/:region_id/:id/params
  class: sfDoctrineRoute
  options:
    type: object
    model: LyraRegionComponent
    method: findItem
  param:
    module: component
    action: Updateparams
  requirements:
    sf_method: [post]

lyra_component_move:
  url: /component/:region_id/:id/:dir
  class: sfDoctrineRoute
  options:
    type: object
    model: LyraRegionComponent
    method: findItem
  param:
    module: component
    action: move
  requirements:
    sf_method: [get]
    dir: 'up|down'

lyra_region:
  class: sfDoctrineRouteCollection
  options:
    model:                LyraRegion
    module:               region
    prefix_path:          /region
    column:               id
    with_wildcard_routes: true

lyra_route:
  class: sfDoctrineRouteCollection
  options:
    model:                LyraRoute
    module:               route
    prefix_path:          /route/:ctype_id
    column:               id
    with_wildcard_routes: true

lyra_menu:
  class: sfDoctrineRouteCollection
  options:
    model:                LyraMenu
    module:               menu
    prefix_path:          /menu
    column:               id
    object_actions:
      up: get
      down: get
    with_wildcard_routes: true

lyra_settings:
  class: sfDoctrineRouteCollection
  options:
    model:                LyraSettings
    module:               settings
    prefix_path:          /settings
    column:               id
    with_wildcard_routes: true

lyra_content_type:
  class: sfDoctrineRouteCollection
  options:
    model:                LyraContentType
    module:               content
    prefix_path:          /content
    column:               id
    with_wildcard_routes: true

lyra_label:
  class: sfDoctrineRouteCollection
  options:
    model:                LyraLabel
    module:               label
    prefix_path:          /label/:catalog_id
    column:               id
    object_actions:
      up: get
      down: get
    with_wildcard_routes: true

lyra_catalog:
  class: sfDoctrineRouteCollection
  options:
    model:                LyraCatalog
    module:               catalog
    prefix_path:          catalog
    column:               id
    object_actions:
      publish: get
      unpublish: get
    with_wildcard_routes: true

lyra_comment:
  class: sfDoctrineRouteCollection
  options:
    model:                LyraComment
    module:               comment
    prefix_path:          comment
    column:               id
    object_actions:
      publish: get
      unpublish: get
    with_wildcard_routes: true

lyra_article:
  class: sfDoctrineRouteCollection
  options:
    model:                LyraArticle
    module:               article
    prefix_path:          /article/:ctype_id
    column:               id
    object_actions:
      publish: get
      unpublish: get
      feature: get
      unfeature: get
    with_wildcard_routes: true

# default rules
homepage:
  url:   /
  param: { module: admpanel, action: index }
    
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
