lyra_settings:
  class: sfDoctrineRouteCollection
  options:
    model:                LyraSettings
    module:               settings
    prefix_path:          /settings
    column:               id
    with_wildcard_routes: true

lyra_content_type:
  class: sfDoctrineRouteCollection
  options:
    model:                LyraContentType
    module:               content
    prefix_path:          /content
    column:               id
    with_wildcard_routes: true

lyra_label:
  class: sfDoctrineRouteCollection
  options:
    model:                LyraLabel
    module:               label
    prefix_path:          /label/:catalog_id
    column:               id
    object_actions:
      up: get
      down: get
    with_wildcard_routes: true

lyra_catalog:
  class: sfDoctrineRouteCollection
  options:
    model:                LyraCatalog
    module:               catalog
    prefix_path:          catalog
    column:               id
    with_wildcard_routes: true

lyra_comment:
  class: sfDoctrineRouteCollection
  options:
    model:                LyraComment
    module:               comment
    prefix_path:          comment
    column:               id
    with_wildcard_routes: true

lyra_article:
  class: sfDoctrineRouteCollection
  options:
    model:                LyraArticle
    module:               article
    prefix_path:          /article/:ctype_id
    column:               id
    object_actions:
      publish: get
      unpublish: get
      feature: get
      unfeature: get
    with_wildcard_routes: true

# default rules
homepage:
  url:   /
  param: { module: admpanel, action: index }
    
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
