<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LyraArticleTable extends Doctrine_Table
{
  public function getFrontPageItems()
  {
    $q = $this->getActiveItemsQuery()
      ->andWhere('a.is_featured = ?', true);
    return $q->execute();
  }
  public function getArchiveDates()
  {
    $q = $this->createQuery('a')
      ->select('YEAR(created_at) ay, MONTH(created_at) am, count(*) ct')
      ->where('a.is_active = ?', true)
      ->addGroupBy('YEAR(created_at), MONTH(created_at)')
      ->addOrderBy('a.created_at DESC');
    return $q->execute();
  }
  public function getArchiveItemsQuery($year, $month)
  {
    $q = $this->createQuery()
      ->where('YEAR(created_at) = ? AND MONTH(created_at) = ? AND is_active = ?',array($year, $month, true))
      ->addOrderBy('created_at DESC');
    return $q;
  }
  public function getActiveItems()
  {
    $q = $this->getActiveItemsQuery();
    return $q->execute();
  }

  public function getActiveItemsQuery()
  {
    return $this->createQuery('a')
      ->where('a.is_active = ?', true)
      ->leftJoin('a.ArticleCreatedBy')
      ->addOrderBy('a.is_sticky DESC, a.created_at DESC');
  }
  public function getBackendItemsQuery(Doctrine_Query $q)
  {
    $rootAlias = $q->getRootAlias();
    $q->leftJoin($rootAlias . '.ArticleCreatedBy u');

    return $q;
  }
  public function findItem($params = array())
  {
    if(!isset($params['slug'])) {
      return false;
    }
    $q = $this->getActiveItemsQuery();
    $q->andWhere($q->getRootAlias() .'.slug = ?', $params['slug']);
    
    return $q->fetchOne();
  }
  public function publish($ids, $on = true)
  {
    $q = $this->createQuery('a')
      ->whereIn('a.id', $ids);

    foreach ($q->execute() as $item) {
      $item->publish($on);
    }
  }
}