<?php

/**
 * LyraRoute
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    lyra
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id$
 */
class LyraRoute extends BaseLyraRoute
{
  public function getParamDefinitionsPath()
  {
    $ctype = $this->getRouteContentType();
    
    $def_file = sfConfig::get('sf_apps_dir') . '/backend/modules/' . $ctype->getModule() . '/config/' . $this->getAction() . '_params.yml';
    if(!file_exists($def_file) && $ctype->getPlugin()) {
      $def_file = sfConfig::get('sf_plugins_dir') . '/' . $ctype->getPlugin() . '/modules/' . $ctype->getModule() . '/config/' . $this->getAction() . '_params.yml';
    }

    return $def_file;
  }
  public function getParameterLevels()
  {
    return array(
      array('type' => 'object', 'def_section' => 'other'),
      array('type' => 'content_type', 'def_section' => 'routes'),

    );
  }
}
