<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LyraCatalog extends BaseLyraCatalog
{
  public function getLabelTree()
  {
    $q = Doctrine_Query::create()
      ->from('LyraLabel l')
      ->where('l.catalog_id = ? and l.level = 0', $this->getId());

    $root = $q->fetchOne();

    return $root->getNode()->getDescendants();
  }
  public function publish($on = true)
  {
    $this->setIsActive($on);
    $this->save();
  }
  public function countLabels()
  {
      return $this->
          getLabelsQuery()->
          count();
  }
  public function getLabelsQuery()
  {
      $q = Doctrine_Query::create()->
          from('LyraLabel l')->
          where('l.catalog_id = ?', $this->getId());

      return $q;
  }
}