<?php

/**
 * LyraRoute
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    lyra
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id$
 */
class LyraRoute extends BaseLyraRoute
{
}
