<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LyraCommentTable extends Doctrine_Table
{
  public function getActiveItemsQuery() {
    $q = $this->createQuery('c');

    $q->andWhere('c.is_active = ?', true);
    $q->addOrderBy('c.created_at DESC');

    return $q;
  }
  public function publish($ids, $on = true)
  {
    $q = $this->createQuery('c')
      ->whereIn('c.id', $ids);

    foreach ($q->execute() as $item) {
      $item->publish($on);
    }
  }
  public function getBackendItemsQuery(Doctrine_Query $q)
  {
    $rootAlias = $q->getRootAlias();
    $q->leftJoin($rootAlias . '.CommentArticle a');

    return $q;
  }
}