<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LyraLabelTable extends Doctrine_Table
{
  public function getActiveItemsQuery()
  {
    return $this->createQuery('l')
      ->where('l.is_active = ?', true);
  }
  public function findItem($params = array())
  {
    if(!isset($params['slug'])) {
      return false;
    }
    $q = $this->getActiveItemsQuery();
    $q->andWhere($q->getRootAlias() .'.slug = ?', $params['slug']);

    return $q->fetchOne();
  }
}