<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LyraCommentTable extends Doctrine_Table
{
  public static function getInstance()
  {
    return Doctrine_Core::getTable('LyraComment');
  }
  public function getActiveItemsQuery() {
    $params = new LyraConfig('settings');

    $q = $this->createQuery('c')
      ->andWhere('c.is_active = ?', true)
      ->addOrderBy('c.created_at' . ($params->get('order_comments', 'comments') == 'date_desc' ? ' DESC' : ''));

    return $q;
  }
  public function publish($ids, $on = true)
  {
    $q = $this->createQuery('c')
      ->whereIn('c.id', $ids);

    foreach ($q->execute() as $item) {
      $item->publish($on);
    }
  }
  public function getBackendItemsQuery(Doctrine_Query $q)
  {
    $rootAlias = $q->getRootAlias();
    $q->leftJoin($rootAlias . '.CommentArticle a');

    return $q;
  }
}