<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LyraArticle extends BaseLyraArticle
{
  public function showReadmore()
  {
    if(trim($this->getContent())) {
      return true;
    }
  }
}