<?php

/**
 * LyraRegionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LyraRegionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LyraRegionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LyraRegion');
    }
    public function getBackendItemsQuery(Doctrine_Query $q)
    {
      $rootAlias = $q->getRootAlias();
      $q->leftJoin($rootAlias. '.RefComponents rc')
        ->leftJoin('rc.Component co')
        ->orderBy($rootAlias . '.id', 'rc.position');
      return $q;
    }
}