<?php

/**
 * LyraComponentVisibilityTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LyraComponentVisibilityTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LyraComponentVisibilityTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LyraComponentVisibility');
    }
}