<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LyraCatalogTable extends Doctrine_Table
{
  public static function getInstance()
  {
    return Doctrine_Core::getTable('LyraCatalog');
  }
}