<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LyraCommentTable extends Doctrine_Table
{
  public function getActiveItemsQuery() {
    $q = $this->createQuery('c');

    $q->andWhere('c.is_active = ?', true);
    $q->addOrderBy('c.created_at DESC');

    return $q;
  }
}