<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LyraArticleLabelTable extends Doctrine_Table
{
  public static function getInstance()
  {
    return Doctrine_Core::getTable('LyraArticleLabel');
  }
}