page_show:
  url: /:slug.html
  class: sfDoctrineRoute
  options:
    type: object
    model: LyraArticle
    method: findItem
  param:
    module: article
    action: show
  requirements:
    sf_method: [get]

page_index:
  url:   /pages
  param:
    module: article
    action: index
    ctype: page

article_show:
  url: /article/:slug.html
  class: sfDoctrineRoute
  options:
    type: object
    model: LyraArticle
    method: findItem
  param:
    module: article
    action: show
  requirements:
    sf_method: [get]

article_index:
  url:   /articles
  param:
    module: article
    action: index
    ctype: article

article_label:
  url: /article/label/:slug
  class: sfDoctrineRoute
  options:
    model: LyraLabel
    type: object
    method: findItem
  param:
    module: article
    action: label
  requirements:
    sf_method: [get]

article_archive:
  url: /article/archive/:year/:month
  class: sfDoctrineRoute
  options:
    type: object
    model: LyraArticle
  param:
    module: article
    action: archive
  requirements:
    year: \d+
    month: \d+
    sf_method: [get]

user_signin:
  url: /user/login
  param:
    module: user
    action: signin

user_signout:
  url: /user/logout
  param:
    module: user
    action: signout
    
# default rules
homepage:
  url:   /
  param:
    module: article
    action: front

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
