prod:
  .settings:
    no_script_name:         true
    logging_enabled:        false

dev:
  .settings:
    error_reporting:        <?php echo (E_ALL | E_STRICT)."\n" ?>
    web_debug:              true
    cache:                  false
    no_script_name:         false
    etag:                   false

test:
  .settings:
    error_reporting:        <?php echo ((E_ALL | E_STRICT) ^ E_NOTICE)."\n" ?>
    cache:                  false
    web_debug:              false
    no_script_name:         false
    etag:                   false

all:
  .settings:
    standard_helpers: [Partial, Cache, I18N]
    i18n: true
    default_culture: en
    enabled_modules: [default, sfGuardAuth, sfContentArchive]
    # Form security secret (CSRF protection)
    csrf_secret:       gfhtyy87     # Unique secret to enable CSRF protection or false to disable

    # Output escaping settings
    escaping_strategy:      true            # Determines how variables are made available to templates. Accepted values: on, off.
    escaping_method:        ESC_SPECIALCHARS # Function or helper used for escaping. Accepted values: ESC_RAW, ESC_ENTITIES, ESC_JS, ESC_JS_NO_ENTITIES, and ESC_SPECIALCHARS.

    # Cache settings
    lazy_cache_key:         on        # Delays creation of a cache key until after checking whether an action or partial is cacheable

  .actions:
    login_module: sfGuardAuth
    login_action: signin