prod:
  .settings:
    no_script_name:         on
    logging_enabled:        off

dev:
  .settings:
    error_reporting:        <?php echo (E_ALL | E_STRICT)."\n" ?>
    web_debug:              on
    cache:                  off
    no_script_name:         off
    etag:                   off

test:
  .settings:
    error_reporting:        <?php echo ((E_ALL | E_STRICT) ^ E_NOTICE)."\n" ?>
    cache:                  off
    web_debug:              off
    no_script_name:         off
    etag:                   off

all:
  .settings:
    standard_helpers: [Partial, Cache, I18N]
    i18n: on
    default_culture: it
    # Form security secret (CSRF protection)
    csrf_secret:       gfhtyy87     # Unique secret to enable CSRF protection or false to disable

    # Output escaping settings
    escaping_strategy:      true            # Determines how variables are made available to templates. Accepted values: on, off.
    escaping_method:        ESC_SPECIALCHARS # Function or helper used for escaping. Accepted values: ESC_RAW, ESC_ENTITIES, ESC_JS, ESC_JS_NO_ENTITIES, and ESC_SPECIALCHARS.

    # Cache settings
    lazy_cache_key:         on        # Delays creation of a cache key until after checking whether an action or partial is cacheable