all:
  is_secure: false

edit:
  is_secure: true
  credentials: [[content_administer,article_administer,article_edit]]
new:
  is_secure: true
  credentials: [[content_administer,article_administer,article_create]]


