generator:
  class: sfDoctrineGenerator
  param:
    model_class:           LyraComment
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          lyra_comment
    with_doctrine_route:     1

    config:
      actions:
        delete:
          credentials: [[comment_administer,comment_delete]]
        publish:
          credentials: [[comment_administer,comment_approve]]
        unpublish:
          credentials: [[comment_administer,comment_approve]]
      fields:  ~
      list:
        title: TITLE_COMMENTS
        display: [comment_article,author_name,content,_published,created_at]
        fields:
          comment_article: {label: TH_ARTICLE_TITLE}
          author_name: {label: TH_AUTHOR_NAME}
          author_email: {label: TH_AUTHOR_EMAIL}
          author_url: {label: TH_AUTHOR_URL}
          content: {label: TH_CONTENT}
          published: {label: TH_PUBLISHED, credentials: [[comment_administer,comment_approve]]}
          created_at: {label: TH_CREATED_AT, date_format: dd.MM.yy hh:ss}
          updated_at: {label: TH_UPDATED_AT, date_format: dd.MM.yy hh:ss}
        object_actions:
          _edit:
            credentials: [[comment_administer,comment_edit]]
          _delete:
            credentials: [[comment_administer,comment_delete]]
        batch_actions:
          _delete:
            credentials: [[comment_administer,comment_delete]]
          publish:
            label: PUBLISH
            credentials: [[comment_administer,comment_approve]]
          unpublish:
            label: UNPUBLISH
            credentials: [[comment_administer,comment_approve]]
        table_method: getBackendItemsQuery
        actions: []
      filter:
        fields:
          article_id: {label: TH_ARTICLE_TITLE}
          is_active: {label: IS_ACTIVE}
        display: [article_id, is_active]
      form:
        class: BackendLyraCommentForm
        display:
          "NONE": [is_active,author_name,author_email,author_url,content]
      edit:    ~
      new:     ~
