params:
  general:
    site_name:
      type: text
    page_title_pfx:
      type: text
    page_title_sfx:
      type: text
  comments:
    moderate_comments:
      type: list
      choices: [moderate_all, moderate_no_auth, moderate_none]
      default: moderate_all

