generator:
  class: sfDoctrineGenerator
  param:
    model_class:           sfGuardUser
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          lyra_user
    with_doctrine_route:     1

    config:
      actions:
        delete:
            credentials: [[user_administer,user_delete]]
      fields:
        username: {label: USERNAME}
        password: {label: PASSWORD}
        password_again: {label: PASSWORD_AGAIN}
        is_active: {label: IS_ACTIVE}
        is_super_admin : {label: IS_SUPER_ADMIN}
        groups_list: {label: GROUPS}
        permissions_list: {label: PERMISSIONS}
      list:
        title: TITLE_USERS
        display: [_username, created_at, updated_at, last_login]
        fields:
          username: {label: TH_USERNAME}
          created_at: {label: TH_CREATED_AT, date_format: dd.MM.yy hh:ss}
          updated_at: {label: TH_UPDATED_AT, date_format: dd.MM.yy hh:ss}
          last_login: {label: TH_LAST_LOGIN, date_format: dd.MM.yy hh:ss}
        object_actions:
          _edit:
            credentials: [[user_administer,user_edit]]
          _delete:
            credentials: [[user_administer,user_delete]]
        actions:
          _new:
            credentials: [[user_administer,user_create]]
        batch_actions:
          _delete:
            credentials: [[user_administer,user_delete]]
      filter:
        display: [username,is_active]

      form:
        class: LyraUserAdminForm
        display:
          "NONE": [username, password, password_again]
          PANEL_PROFILE: [user_profile]
          PANEL_PERMISSIONS: [is_active, is_super_admin, groups_list, permissions_list]

      edit:
        title: Editing User "%%username%%"

      new:
        title: New User