params:
  latest:
    max:
      type: text
      size: 1
      max_length: 3
      default: 5
    feed:
      type: text
  labels:
    catalog:
      type: text
  archive:
    max_years:
      type: text
      size: 2
      max_length: 3
    show_counters:
      type: boolean
      default: true
