generator:
  class: sfDoctrineGenerator
  param:
    model_class:           LyraArticle
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          lyra_article
    with_doctrine_route:     1

    config:
      actions: ~
      fields:  ~
      list:
        title: TITLE_ARTICLES
        display: [=title,_comments,_published,_front_page,created_at,article_created_by,id]
        fields:
          title: {label: TH_TITLE}
          comments: {label: TH_COMMENTS}
          published: {label: TH_PUBLISHED}
          created_at: {label: TH_CREATED_AT, date_format: dd.MM.yy hh:mm}
          updated_at: {label: TH_UPDATED_AT, date_format: dd.MM.yy hh:mm}
          article_created_by: {label: TH_AUTHOR_NAME}
          id: {label: TH_ID}
        batch_actions:
          _delete: ~
          publish: {label: PUBLISH}
          unpublish: {label: UNPUBLISH}
        table_method: getBackendItemsQuery
      filter:
        fields:
          title: {label: TITLE}
          is_active: {label: IS_ACTIVE}
        display: [title,is_active]
      form:
        class: BackendLyraArticleForm
        display:
          "NONE": [ctype_id, title, subtitle, slug, path]
          PANEL_CONTENT: [content]
          PANEL_SUMMARY: [summary]
          PANEL_PUBLISH: [is_active, is_featured, is_sticky, is_archived, is_feeded, publish_start, publish_end]
          PANEL_LABELS: [labels]
          PANEL_METATAGS: [meta_title, meta_descr, meta_keys, meta_robots]
          PANEL_PARAMS: [lyra_params]
      edit:
        title: TITLE_EDIT_ARTICLE
      new:
        title: TITLE_NEW_ARTICLE
