params:
  route: ~
  other:
    max_items:
      type: text
    sort_field:
      type: list
      choices: [title, updated_at, created_at]
    sort_order:
      type: list
      choices: [asc, desc]
