params:
  item:
    linked_title:
      type: boolean
      default: true
    show_read_more:
      type: boolean
      default: true
    show_author:
      type: boolean
      default: true
    show_date:
      type: boolean
      default: true
    date_format:
      type: text
      size: 15
      default: d MMMM, yyyy
    allow_comments:
      type: boolean
      default: true
    allow_anonymous_comments:
      type: boolean
      default: true
      levels: [content_type]
    show_comments:
      type: boolean
      default: true
    date_comments:
      type: text
      size: 15
      default: d MMMM, yyyy
    time_comments:
      type: text
      size: 6
      default: H:mm
    author_url_comments:
      type: boolean
      default: true
      levels: [content_type]
    capture_email_comments:
      type: boolean
      default: true
      levels: [content_type]
    capture_name_comments:
      type: boolean
      default: true
      levels: [content_type]
  lists:
    defaults:
      max_items:
        type: text
        default: 25
      sort_field:
        type: list
        choices: [title, updated_at, created_at]
        default: created_at
      sort_order:
        type: list
        choices: [asc, desc]
        default: asc
    index:
      route: ~
      other:
        max_items:
          type: text
        sort_field:
          type: list
          choices: [title, updated_at, created_at]
        sort_order:
          type: list
          choices: [asc, desc]
    archive:
      route:
        year:
          type: text
          size: 4
          max_length: 4
          required: true
        month:
          type: text
          size: 2
          max_length: 3
          required: true
      other:
        max_items:
          type: text
          size: 2
          max_length: 3
        sort_field:
          type: list
          choices: [title, updated_at, created_at]
        sort_order:
          type: list
          choices: [asc, desc]
    label:
      route:
        slug:
          type: text
      other:
        max_items:
          type: text
        sort_field:
          type: list
          choices: [title, updated_at, created_at]
        sort_order:
          type: list
          choices: [asc, desc]

