generator:
  class: sfDoctrineGenerator
  param:
    model_class:           LyraRegion
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          lyra_region
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: 'Regions / Components'
        table_method: getBackendItemsQuery
        display: [name]
        actions: {}
        object_actions:
          _edit: {label: 'Add Component'}
        batch_actions: {}
      filter:
        class: false
      form:    ~
      edit:    ~
      new:     ~
